version: "3.9"
services: 
  web:
    build: ./frontend
    depends_on: 
      - api
    ports:
      - 3000:3000
    restart: always
    volumes: 
      - ./frontend/src:/app/src/
    networks: 
      - bookznet
  api:
    depends_on: 
      - db
    build: ./backend
    ports:
      - 8000:8000
    restart: always
    volumes: 
      - ./backend/.env:.env
    networks: 
      - bookznet
  db:
    image: postgres:13.3-alpine3.14
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recommerce
    networks: 
      - bookznet
networks: 
  bookznet:
volumes: 
  pgdata: